### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by GrayTempest-400** [mrathena/python.yolo.apex.autoaim.helper#3]
FileNotFoundError: [Errno 2] No such file or directory: 'weights.apex.private.crony.1435244588.1127E7B7107206013DE38A10EDDEEEB3-v5-n-416-50000-3-0.1.2.engine'
这个.engine文件是要自己训练吗

**Comment by zhaoyihe031** [comment]
您好，我是何炤毅，你的来件我已收到，我会在阅读后尽快给您回复。谢谢~

**Comment by GrayTempest-400** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'weights.apex.private.crony.1435244588.1127E7B7107206013DE38A10EDDEEEB3-v5-n-416-50000-3-0.1.2.engine' 这个.engine文件是项目中没有要自己训练吗
